var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+b++,e)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(e){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){var e=$jscomp.makeIterator(a),f=e.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=e,this.yield(f.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var e=this.finallyContexts_.splice(b||0)[0];if(e=this.abruptCompletion_=this.abruptCompletion_||e){if(e.isException)return this.jumpToErrorHandler_();void 0!=e.jumpTo&&this.finallyAddress_<e.jumpTo?(this.nextAddress=e.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,e){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var d=f.value}catch(k){return this.context_.yieldAllIterator_=null,this.context_.throw_(k),this.nextStep_()}this.context_.yieldAllIterator_=null;e.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var e=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(e,a.prototype);return e};
$jscomp.polyfill=function(a,b,e,f){if(b){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];d in e||(e[d]={});e=e[d]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(a){return a instanceof d?a:new d(function(c,b){c(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})}this.batch_.push(a)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){f(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var h=a[b];a[b]=null;try{h()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(h){c.reject(h)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(c){h||(h=!0,a.call(b,c))}}var b=this,h=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var c=void 0;try{c=a.then}catch(h){this.reject_(h);return}"function"==typeof c?
this.settleSameAsThenable_(c,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)k.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var k=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(n){c.reject(n)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(p){g(p)}}:b}var e,g,f=new d(function(a,b){e=a;g=b});this.callWhenSettled_(c(a,e),c(b,g));return f};
d.prototype["catch"]=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?k.asyncExecute(c):this.onSettledCallbacks_.push(c)};d.resolve=e;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,c){for(var d=$jscomp.makeIterator(a),h=d.next();!h.done;h=
d.next())e(h.value).callWhenSettled_(b,c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?e([]):new d(function(a,d){function h(b){return function(c){l[b]=c;f--;0==f&&a(l)}}var l=[],f=0;do l.push(void 0),f++,e(c.value).callWhenSettled_(h(l.length-1),d),c=b.next();while(!c.done)})};return d},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}},"es9","es3");$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function e(b){return a["throw"](b)}return new Promise(function(f,d){function k(a){a.done?f(a.value):Promise.resolve(a.value).then(b,e).then(k,d)}k(a.next())})};
$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var puppeteer=require("puppeteer"),fs=require("fs-extra"),sanitize=require("sanitize-filename"),path=require("path"),request=require("request").defaults({jar:!0}),progress=require("request-progress"),term=require("terminal-kit").terminal,cheerio=require("cheerio"),_options={"forzar-redescarga":!1,"login-url":"https://aulavirtual.fio.unam.edu.ar/login/index.php","curso-url":"https://aulavirtual.fio.unam.edu.ar/enrol/index.php?id=83",username:"pache_08",password:"cuadrichanchoA0."},__config={width:1280,
height:300};
(function(){function a(){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){switch(c.nextAddress){case 1:return c.yield(d.cookies(),2);case 2:return b=c.yieldResult,c.yield(d.type("#username",_options.username),3);case 3:return c.yield(d.type("#password",_options.password),4);case 4:return c.yield(d.waitFor(1E3),5);case 5:return console.info("  \u00bb Iniciando sesi\u00f3n en la cuenta..."),c.yield(Promise.all([d.click("#loginbtn"),d.waitForNavigation({waitUntil:"networkidle2"})]),6);
case 6:return c.yield(d.cookies(),7);case 7:if(k=c.yieldResult,k[0].value!==b[0].value)term.brightGreen("  \u2713 Autenticaci\u00f3n concedida.\n\n"),c.jumpTo(0);else return term.brightYellow("  \u26a0\ufe0f Se produjo un error en la autenticaci\u00f3n, reintentando...\n\n"),c.yield(a(),0)}})}function b(){function a(a){a=cheerio.load(a);var b="";0<a(".resourcecontent").length?b=a(".resourcecontent").html().match(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/gi)[0]:
0<a(".resourceworkaround").length?b=a(".resourceworkaround").html().match(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/gi)[0]:0<a(".singlebutton > form:nth-child(1)").length?b=a(".singlebutton > form:nth-child(1)").attr("action"):0<a(".urlworkaround").length&&(b=a(".urlworkaround").html().match(/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/gi)[0]);if(null===b||""===b)term.brightYellow("\t    \u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\u2584\n"),
term.brightYellow("\t    \u26a0\ufe0f Atenci\u00f3n: No se pudo obtener la direcci\u00f3n del recurso. Se\n"),term.brightYellow("\t    descargar\u00e1 una imagen con un s\u00edmbolo  de 'error' en su lugar\n"),term.brightYellow("\t    \u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\u2580\n"),
b="https://upload.wikimedia.org/wikipedia/commons/5/5f/Icon_Simple_Error.png";return b}return new Promise(function(b,d){(function m(d,e){e=void 0===e?!1:e;var l={url:c[d].fileLink,headers:{Cookie:k[0].name+"="+k[0].value},rejectUnauthorized:!1,method:e?"GET":"HEAD"};null!==c[d].isMoodleFolder_id&&(l.strictSSL=!1,l.qs={id:c[d].isMoodleFolder_id});request(l,function(l,f){if(l)console.error("  \u2716 ["+(d+1)+"/"+c.length+"] "+c[d].fileTitle+"  \u2192  Error. Reitentando..."),m(d);else{if(f.headers["content-disposition"]){var h=
f.headers["content-disposition"].match(/filename="([^"]*)"/gi)[0].split(".");1<h.length&&(fileExtension=h.slice(-1).toString().slice(0,-1),c[d].fileName=c[d].fileName+"."+fileExtension,c[d].originalFileName=h[0].split('"').slice(-1).toString()+"."+fileExtension)}f.headers["content-length"]&&(c[d].fileSize=+f.headers["content-length"]);f.headers["content-type"]&&(c[d].contentType=f.headers["content-type"],!1===e&&console.log("\n    ["+(d+1)+"/"+c.length+"] "+c[d].sectionName+':\n\t    Nombre: "'+c[d].fileTitle+
'"\n\t    Tipo: '+f.headers["content-type"]),-1!=f.headers["content-type"].indexOf("html")?""==f.body?(console.log("\t    El link conduce a un archivo HTML: Obteniendo recurso real..."),m(d,!0)):(h=a(f.body),c[d].fileLink=h,console.log('\t    Recurso real: "...'+h.slice(-50)+'"'),console.log("\t    Obteniendo informaci\u00f3n del archivo..."),m(d)):d+1<c.length?m(d+1):(term.brightGreen("\n  \u2713 Archivos analizados.\n"),console.log("    Peso total de los recursos: "+(c.reduce(function(a,b){return{fileSize:a.fileSize+
b.fileSize}}).fileSize/1E6).toFixed(2)+" MB.\n\n"),b()))}})})(0)})}function e(){return new Promise(function(a,b){function d(b){b+1<c.length?f(b+1):(term.brightGreen("\n  \u2713 Descargados todos los archivos. Pod\u00e9s encontrarlos en la carpeta:\n\n"),term.brightBlue.bold('    "./descargas/'+c[0].courseName+' - Aula Virtual"\n\n'),a())}function e(a){var b=path.join("descargas",c[a].courseName+" - Aula Virtual",c[a].sectionName,c[a].subSectionName,c[a].fileName);try{if(fs.accessSync(b,fs.constants.F_OK),
+fs.statSync(b).size===c[a].fileSize)return!0}catch(q){return!1}}function f(a){if(e(a)&&!_options["forzar-redescarga"])term.bold("    ["+(a+1)+"/"+c.length+"] "+c[a].fileTitle+": ").brightGreen("Ya descargado previamente.\n\n"),d(a);else{var b=term.progressBar({eta:!0,percent:!0,title:"    ["+(a+1)+"/"+c.length+"] "+c[a].fileTitle,barStyle:term.brightGreen}),f={url:c[a].fileLink,headers:{Cookie:k[0].name+"="+k[0].value},rejectUnauthorized:!1,method:"GET"};null!==c[a].isMoodleFolder_id&&(f.strictSSL=
!1,f.qs={id:c[a].isMoodleFolder_id});progress(request(f,function(e,f){e&&(b&&b.stop(),term.bold.brightRed("    ["+(a+1)+"/"+c.length+"] "+c[a].fileTitle+": Error.\n\n"),d(a))}),{}).on("progress",function(a){b.update(a.percent)}).on("error",function(a){}).on("end",function(){b.update(1);b.stop();console.log("\n");d(a)}).pipe(fs.createWriteStream(path.join("descargas",c[a].courseName+" - Aula Virtual",c[a].sectionName,c[a].subSectionName,c[a].fileName)))}}f(0)})}var f,d,k,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:return console.info("\n\u00bb INICIANDO PROCESO\n"),
g.yield(puppeteer.launch({headless:!0,args:["--window-size="+__config.width+","+__config.height]}),2);case 2:return f=g.yieldResult,process.on("unhandledRejection",function(a,b){console.error("\n  \u2716 Se produjo un error: Rechazo de promesa no manejado.")}),g.yield(f.newPage(),3);case 3:return d=g.yieldResult,g.yield(d.setCacheEnabled(!0),4);case 4:return g.setCatchFinallyBlocks(5),console.info("  \u00bb Intentando conectarse con el aula virtual..."),g.yield(d["goto"](_options["login-url"],{waitUntil:"networkidle2"}),
7);case 7:term.brightGreen("  \u2713 Conexi\u00f3n establecida.\n\n");g.leaveTryBlock(6);break;case 5:g.enterCatchBlock(),console.error("  \u2716 No fu\u00e9 posible conectarse con el aula virtual."),f.close();case 6:return g.yield(a(),8);case 8:return console.info("  \u00bb Obteniendo lista de recursos disponibles para la descarga..."),g.yield(d["goto"](_options["curso-url"],{waitUntil:"networkidle2"}),9);case 9:return g.yield(d.addScriptTag({path:"jquery-3.2.1.min.js"}),10);case 10:return g.yield(d.evaluate(function(){var a=
function l(){var a,b,c;return $jscomp.generator.createGenerator(l,function(d){1==d.nextAddress&&(a=2,b=0,c=!1);if(4!=d.nextAddress)return d.yield("hsl("+360*b/a+", 30%, 50%, 0.5)",4);b++;!0===c&&b++;b>=a&&(b=1,a*=2,c=!0);return d.jumpTo(2)})}();_BLACKLIST_TIPOS="https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/forum/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/page/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/feedback/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/attendance/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/url/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/assign/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/quiz/1551107122/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/core/1551954692/f/sourcecode-24 https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/lesson/1551954692/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/more/page/1551954692/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/more/url/1551954692/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/more/core/1551954692/f/sourcecode-24 https://aulavirtual.fio.unam.edu.ar/theme/image.php/more/data/1551954692/icon https://aulavirtual.fio.unam.edu.ar/theme/image.php/clean/glossary/1551954692/icon".split(" ");
_BLACKLIST_TIPOS=_BLACKLIST_TIPOS.map(function(a){return a.replace(/\/\d+(?=\/)/gi,"")});var b=$(".page-header-headings").text();a.next();var c=jQuery("body .instancename").closest("a").filter(function(a,b){var c=jQuery(b).find("img").attr("src").replace(/\/\d+(?=\/)/gi,"");-1===_BLACKLIST_TIPOS.indexOf(c)&&jQuery(b).css({background:"#00ff1936","border-radius":"5px",padding:"5px 10px"});return-1===_BLACKLIST_TIPOS.indexOf(c)}).map(function(c,d){var e=jQuery(d).attr("href").replace(/(^\s+|\s+$)/gi,
""),f=$(d).closest(".course-content ul li.section.main").css("border","2px dashed green").attr("aria-label").replace(/(^\s+|\s+$)/gi,""),h=$(d).text().replace(new RegExp($(d).find(".accesshide").text()+"$"),"").replace(/(^\s+|\s+$)/gi,""),g="",k=$(d).closest(".activity");$(d).closest(".activity").next();do{var l=k;k=l.prev();l=l.closest(".course-content ul li.section.main").attr("aria-label");var m=k.closest(".course-content ul li.section.main").attr("aria-label");if(k.hasClass("modtype_label")){g=
k.text().replace(/(^\s+|\s+$)/gi,"");a.next();break}}while(l===m);return{fileLink:e,fileName:h,fileTitle:h,sectionName:f,subSectionName:g,courseName:b,originalFileName:"",contentType:"",fileSize:null,isMoodleFolder_id:1<e.split("id=").length&&-1!=e.indexOf("folder")?e.split("id=").slice(-1)[0]:null}}).toArray();console.table(c);return c}),11);case 11:return c=g.yieldResult,term.brightGreen("  \u2713 Total de archivos a descargar: "+c.length+"\n\n"),c=c.map(function(a){return Object.assign(a,{fileName:sanitize(a.fileName,
{replacement:"-"}),fileTitle:sanitize(a.fileTitle,{replacement:"-"}),sectionName:sanitize(a.sectionName,{replacement:"-"}),subSectionName:sanitize(a.subSectionName,{replacement:"-"})})}),c.forEach(function(a){return fs.ensureDirSync(path.join("descargas",a.courseName+" - Aula Virtual",a.sectionName,a.subSectionName))}),console.info("  \u00bb Guardando una vista previa del curso..."),g.yield(d._client.send("Emulation.clearDeviceMetricsOverride"),12);case 12:return g.yield(d.screenshot({path:"./descargas/"+
c[0].courseName+" - Aula Virtual/Contenido del curso.png",fullPage:!0}),13);case 13:return g.yield(d.pdf({path:"./descargas/"+c[0].courseName+" - Aula Virtual/Contenido del curso.pdf",format:"A4",printBackground:!0}),14);case 14:return term.brightGreen('  \u2713 Guardada en "./descargas/'+c[0].courseName+' - Aula Virtual/Contenido del curso.png"\n\n'),console.info("  \u00bb Analizando tipos de archivos..."),g.yield(b(),15);case 15:return console.info("  \u00bb Descargando archivos:\n"),g.yield(e(),
16);case 16:return console.info("\n\u00bb FINALIZANDO PROCESO\n"),g.yield(f.close(),0)}})})();